#!/bin/bash

if [ -z "$1" ]
then
  printf "Required directory to archive"
  exit 1
else
  if [ $1 = "-h" ]
  then
    printf "\narchive_this [directory to archive] [(Optional) name of archive]\n"
    printf "Default archive name: \"archive.tar.zst\"\n\n"
    exit 0
  else
    name=""
    if [ -z "$2" ]
    then
      name=archive.tar.zst
    else
      name="$2"
    fi
    tar --zstd -cf $name $1
    printf "\nArchive created: $name\n\n"
    exit 0
  fi
fi
